[package]
name = "brak-ir-mir"
version = "0.1.0"
edition = "2021"
description = "Brak Mid-level IR: CFG, basic blocks, flat instructions"

[dependencies]
brak-core = { path = "../brak-core" }
brak-ir-hir = { path = "../brak-ir-hir" }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
brak-frontend = { path = "../brak-frontend" }
brak-ir-ast = { path = "../brak-ir-ast" }
